version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: pesapulse-postgres
    environment:
      - POSTGRES_USER=pesapulse
      - POSTGRES_PASSWORD=sct212-0053-2021
      - POSTGRES_DB=transaction_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  mongo:
    image: mongo:8.0
    container_name: pesapulse-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pesapulse
      - MONGO_INITDB_ROOT_PASSWORD=sct212-0053-2021
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  postgres_data:
  mongo_data: