version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: pesapulse-postgres
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=pesapulse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=transaction_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  mongo:
    image: mongo:8.0
    container_name: pesapulse-mongo
    env_file:
      - ../.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  postgres_data:
  mongo_data: